version: '3'
services:
  frontend:
    image: sourcemapteam/frontend:latest
    container_name: frontend
    networks:
      - app-network

  strapi-cms:
    image: sourcemapteam/strapi:latest
    container_name: strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_NAME=cms
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=cms
      - DATABASE_PASSWORD=cms
      - AUTHENTICATION_DATABASE=cms 
    volumes:
      - ./app:/srv/app
      - ./app/uploads:/public/uploads
    depends_on:
      - mysql
    networks:
      - app-network

  epd:
    image: sourcemapteam/nest
    container_name: nest
    ports:
      - "3334:3334"
    networks:
      - app-network 

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  
      - "1337:1337"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email babanov.js@gmail.com --agree-tos --no-eff-email --force-renewal -d 375526-ch23320.tmweb.ru -d www.375526-ch23320.tmweb.ru

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: cms
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: cms
    volumes:
      - ./data:/data/db
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:      
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/app/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/app/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge

